version: "3.1"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_USER: development
      MYSQL_PASSWORD: development
      MYSQL_DATABASE: task_mate
    ports:
      - 0.0.0.0:3306:3306
    networks:
      - symfony_network
  adminer_php:
    image: dockette/adminer:mysql
    ports:
      - 8006:80
    depends_on:
      - mysql
    networks:
      - symfony_network
networks:
  symfony_network:
